name: Cherry Pick Label Check

on:
  pull_request:
    types: 
      - labeled
      - unlabeled
      - opened
      - synchronize
    branches:
      - master

jobs:
  cherry-pick-label-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check labels
        run: |
            labels=$(jq -r '.pull_request.labels[].name' $GITHUB_EVENT_PATH)
            if [[ ! $labels == *cherry-pick-to-* ]]; then
                echo "No label starting with 'cherry-pick-to-' found."
                exit 1
            fi
